### ISSUE TITLE
Les placeholders dans les formulaires ne sont pas logique

### ISSUE THREAD

**Issue by mattheop** [Mattheop/IUT-ESporter#1]
Tous les champs on un placeholder identique ou vide
![image](https://user-images.githubusercontent.com/24438303/218415414-0597c5f8-f357-44b1-8a43-ebeef133a4f2.png)

**Comment by mattheop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revoir les formulaire pour y mettre un place Holder](https://trello.com/c/me8RmhkZ/125-revoir-les-formulaire-pour-y-mettre-un-place-holder)

**Comment by Akenosss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Formulaire ajouter & modif un joueur](https://trello.com/c/NluHiwic/11-formulaire-ajouter-modif-un-joueur)
