### ISSUE TITLE
Certaines pages n'ont pas de titre personnalisé

### ISSUE THREAD

**Issue by Akenosss** [Mattheop/IUT-ESporter#13]
Titre par défaut = 'title'

**Comment by Akenosss** [comment]
![image](https://user-images.githubusercontent.com/116635028/218437142-6c993f50-98e7-4ff6-89ee-63c96f6c5cbd.png)

**Comment by mattheop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pages n'ont pas de titre pour le navigateur](https://trello.com/c/Nm4SDUqx/18-pages-nont-pas-de-titre-pour-le-navigateur)
