### ISSUE TITLE
Page d'accueil vide pour chaque rôle

### ISSUE THREAD

**Issue by Akenosss** [Mattheop/IUT-ESporter#17]
![image](https://user-images.githubusercontent.com/116635028/219375404-6271afee-5be6-43ba-8e52-92d37b9a0abd.png)

**Comment by mattheop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Page d'accueil pour chaque rôle est vide](https://trello.com/c/prOBrcP5/1-page-daccueil-pour-chaque-r%C3%B4le-est-vide)
