### ISSUE TITLE
Titre dashboard incorrect (arbitre = organisateur)

### ISSUE THREAD

**Issue by Akenosss** [Mattheop/IUT-ESporter#9]

**Comment by Akenosss** [comment]
![image](https://user-images.githubusercontent.com/116635028/218427101-a4a599a2-fcae-47e4-bc46-4aacf6b8902c.png)

**Comment by Akenosss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Titre page arbitre = organisateur](https://trello.com/c/qh51thRQ/136-titre-page-arbitre-organisateur)

**Comment by mattheop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pages n'ont pas de titre pour le navigateur](https://trello.com/c/Nm4SDUqx/18-pages-nont-pas-de-titre-pour-le-navigateur)
